# IMPORTAR LIBRERIAS

In [2]:
import pandas as pd
import matplotlib.pyplot as plt  
import seaborn as sns
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from xgboost import XGBClassifier

import warnings
warnings.filterwarnings("ignore")

#
___

# DATA SETS - LECTURA

In [ ]:
df_academico_train = pd.read_csv("../01_data/03_train/ds_academico_train.csv", sep=",") 
df_academico_train.head() 

Daytime/evening attendance  Previous qualification  \
0                           0                       1   
1                           1                       1   
2                           1                       1   
3                           0                       3   
4                           1                       1   

   Previous qualification (grade)  Mother's qualification  \
0                               2                       3   
1                               2                       1   
2                               2                       1   
3                               2                       2   
4                               2                       3   

   Father's qualification  Admission grade  Educational special needs  Debtor  \
0                       3                2                          0       0   
1                       1                2                          0       0   
2                       1                2                          0       1   
3                       1                3                          0       0   
4                       3                2                          0       0   

   Tuition fees up to date  Gender  ...  Curricular units 1st sem (enrolled)  \
0                        1       0  ...                                    5   
1                        1       1  ...                                    7   
2                        0       0  ...                                   10   
3                        1       0  ...                                    5   
4                        1       1  ...                                    6   

   Curricular units 1st sem (evaluations)  \
0                                       7   
1                                       9   
2                                      16   
3                                       0   
4                                       8   

   Curricular units 1st sem (approved)  Curricular units 1st sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.342857   
2                                    6                         11.833333   
3                                    0                          0.000000   
4                                    6                         12.000000   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    5   
1                                    0                                    8   
2                                    2                                    7   
3                                    0                                    5   
4                                    0                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       8   
1                                      10   
2                                       8   
3                                       0   
4                                       8   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                              0.00   
1                                    7                             11.65   
2                                    2                             13.00   
3                                    0                              0.00   
4                                    6                             11.50   

   Target  
0       0  
1       1  
2       0  
3       0  
4       1  

[5 rows x 24 columns]

In [4]:
df_academico_test = pd.read_csv("../01_data/04_test/ds_academico_test.csv", sep=",") 
df_academico_test.head()

Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           1                       1   

   Previous qualification (grade)  Mother's qualification  \
0                               2                       2   
1                               2                       3   
2                               3                       1   
3                               2                       2   
4                               2                       2   

   Father's qualification  Admission grade  Educational special needs  Debtor  \
0                       2                2                          0       0   
1                       3                2                          0       1   
2                       1                3                          0       0   
3                       1                2                          0       0   
4                       2                2                          0       0   

   Tuition fees up to date  Gender  ...  Curricular units 1st sem (credited)  \
0                        1       0  ...                                    0   
1                        0       0  ...                                    0   
2                        1       0  ...                                    0   
3                        1       0  ...                                    0   
4                        1       1  ...                                    0   

   Curricular units 1st sem (enrolled)  \
0                                    5   
1                                    6   
2                                    7   
3                                    7   
4                                    6   

   Curricular units 1st sem (evaluations)  \
0                                      11   
1                                       8   
2                                       8   
3                                       9   
4                                       7   

   Curricular units 1st sem (approved)  Curricular units 1st sem (grade)  \
0                                    3                         10.666667   
1                                    6                         14.142857   
2                                    4                         12.000000   
3                                    5                         13.850000   
4                                    0                          0.000000   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    5   
1                                    0                                    6   
2                                    0                                    8   
3                                    0                                    8   
4                                    0                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       9   
1                                       6   
2                                       8   
3                                       9   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  
0                                    4                         10.250000  
1                                    5                         12.000000  
2                                    0                          0.000000  
3                                    7                         12.192857  
4                                    0                          0.000000  

[5 rows x 23 columns]

#
___

# ENTRENAMIENTO

In [6]:
X = df_academico_train.drop(columns=['Target'])  
y = df_academico_train['Target']                 


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
# Crear un diccionario para almacenar los modelos y sus resultados
modelos = {}
resultados = {}

# 1. Logistic Regression
logreg = LogisticRegression(C=1.0, penalty='l2', solver='liblinear', random_state=42)
logreg.fit(X_train, y_train)
y_pred_logreg = logreg.predict(X_test)

# Almacenar el modelo y los resultados
modelos['Logistic Regression'] = logreg
resultados['Logistic Regression'] = {
    "Accuracy": accuracy_score(y_test, y_pred_logreg),
    "Classification Report": classification_report(y_test, y_pred_logreg),
    "Confusion Matrix": confusion_matrix(y_test, y_pred_logreg)
}

# 2. Random Forest
rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

# Almacenar el modelo y los resultados
modelos['Random Forest'] = rf
resultados['Random Forest'] = {
    "Accuracy": accuracy_score(y_test, y_pred_rf),
    "Classification Report": classification_report(y_test, y_pred_rf),
    "Confusion Matrix": confusion_matrix(y_test, y_pred_rf)
}

# 3. Gradient Boosting (XGBoost)
xgb = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)

# Almacenar el modelo y los resultados
modelos['XGBoost'] = xgb
resultados['XGBoost'] = {
    "Accuracy": accuracy_score(y_test, y_pred_xgb),
    "Classification Report": classification_report(y_test, y_pred_xgb),
    "Confusion Matrix": confusion_matrix(y_test, y_pred_xgb)
}

# 4. Support Vector Machine (SVM)
svm = SVC(C=1.0, kernel='rbf', gamma='scale', random_state=42)
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

# Almacenar el modelo y los resultados
modelos['Support Vector Machine'] = svm
resultados['Support Vector Machine'] = {
    "Accuracy": accuracy_score(y_test, y_pred_svm),
    "Classification Report": classification_report(y_test, y_pred_svm),
    "Confusion Matrix": confusion_matrix(y_test, y_pred_svm)
}

# 5. k-Nearest Neighbors (k-NN)
knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

# Almacenar el modelo y los resultados
modelos['k-Nearest Neighbors'] = knn
resultados['k-Nearest Neighbors'] = {
    "Accuracy": accuracy_score(y_test, y_pred_knn),
    "Classification Report": classification_report(y_test, y_pred_knn),
    "Confusion Matrix": confusion_matrix(y_test, y_pred_knn)
}

# Imprimir los resultados de cada modelo
for nombre, resultado in resultados.items():
    print(f"Modelo: {nombre}")
    print("Accuracy:", resultado["Accuracy"])
    print("\nClassification Report:\n", resultado["Classification Report"])
    print("Confusion Matrix:\n", resultado["Confusion Matrix"])
    print("\n" + "-"*50 + "\n")

Modelo: Logistic Regression
Accuracy: 0.9174311926605505

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.84      0.89       402
           1       0.90      0.97      0.93       579

    accuracy                           0.92       981
   macro avg       0.93      0.91      0.91       981
weighted avg       0.92      0.92      0.92       981

Confusion Matrix:
 [[337  65]
 [ 16 563]]

--------------------------------------------------

Modelo: Random Forest
Accuracy: 0.908256880733945

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.83      0.88       402
           1       0.89      0.96      0.93       579

    accuracy                           0.91       981
   macro avg       0.91      0.90      0.90       981
weighted avg       0.91      0.91      0.91       981

Confusion Matrix:
 [[335  67]
 [ 23 556]]

--------------------------------------------------


In [5]:
# Separar en características (X) y variable objetivo (y)
X = df_academico_train.drop(columns=['Target'])  # Cambia 'Target' por el nombre de tu columna objetivo
y = df_academico_train['Target']                 # Cambia 'Target' por el nombre de tu columna objetivo

# Dividir en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Crear y entrenar el modelo de Árbol de Decisión
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Realizar predicciones
y_pred = model.predict(X_test)

# Evaluación del modelo
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8409785932721713

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.83      0.81       402
           1       0.88      0.85      0.86       579

    accuracy                           0.84       981
   macro avg       0.83      0.84      0.84       981
weighted avg       0.84      0.84      0.84       981


Confusion Matrix:
 [[335  67]
 [ 89 490]]


#
___

# PRUEBA CON TEST

In [ ]:
predicciones_submit = best_model.predict(df_academico_test)

df_academico_test['SeriousDlqin2yrs'] = predicciones_submit

# df_resultados = df_academico_test[['SeriousDlqin2yrs']].reset_index()